### ISSUE TITLE
Inactive menus

### ISSUE THREAD

**Issue by AsherMaximum** [rozboris/Sublime-Tweet#4] opened 2012-01-13 01:11 UTC
After installation, the menu items are both grayed out. Also, the commands do not show up in command palette.

**Comment by mrjabba** [comment] 2012-01-19 16:52
Mine is grayed out as well. I'm using Beta, Build 2165 on Ubuntu 11.10. I may try this on Arch later to see if there' a difference. Has this been tested on Linux before? Is there an error or output file I can check?

**Comment by mrjabba** [comment] 2012-01-19 16:54
Found it on the Sublime console.

Reloading plugin /home/mrjabba/.Sublime Text 2/Packages/Sublime Tweet/SublimeTweet.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 59, in reload_plugin
  File "./SublimeTweet.py", line 5, in <module>
    import libs.twitter
  File "./libs/twitter.py", line 66, in <module>
    import oauth2 as oauth
  File "./libs/oauth2.py", line 31, in <module>
    import httplib2
  File "./libs/httplib2.py", line 795, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'

Is this a version of Python problem?
This what I see when I invoke python.

Python 2.7.2+ (default, Oct  4 2011, 20:06:09) 
[GCC 4.6.1] on linux2

**Comment by ianleckey** [comment] 2012-05-22 10:52
Seems sublime uses 2.6, so won't matter what your 2.7 version has been built with

**Comment by Erwyn** [comment] 2012-06-20 09:59
same problem here, grayed as well. Any solution?

**Comment by Erwyn** [comment] 2012-06-20 11:33
I have to precise that I have the same error than mrjabba

**Comment by Erwyn** [comment] 2012-06-21 07:13
After looking through the web, I found out that it was a question of http not compiled with ssl in the linux package of sublime text. However I don't know how to correct it.

**Comment by kracekumar** [comment] 2012-09-13 08:42
The issue is sublime2 ships python with `.pyo` file, untar `sublime2` for linux and unzip `Sublime Text 2/lib/python26.zip` you will find `*.pyo` files, sublime2 built with `python 2.6.6`, 

```

>>> sys.version
'2.6.7 (r267:88850, Aug 11 2011, 12:16:10) \n[GCC 4.6.1]'
>>> httplib.HTTPSConnection
<class httplib.HTTPSConnection at 0xb743865c>
```

`HTTPSConnection is available in 2.6.7`, one  hack is to replace the httplib with `requests`, I know lot of work is needed.

**Comment by salmankhwaja** [comment] 2013-08-14 12:03
I am having the same problem.
Restarted the Sublime Text. Didn't ask me the Twitter Username / Password.
TOOLS > Tweet and TOOLS > Read Timeline are greyed out. Disabled. 
Command Pallette is not showing anything when Twitter is typed.

![screenshot-untitled public_html - sublime text 2 unregistered -1](https://f.cloud.github.com/assets/702831/961571/68ab9804-04d9-11e3-9ddf-89844302aaf1.png)
![screenshot-untitled public_html - sublime text 2 unregistered](https://f.cloud.github.com/assets/702831/961574/6d9220b8-04d9-11e3-9ef2-f40c0b1d9cf5.png)

**Comment by rozboris** [comment] 2014-02-12 07:29
It was greyed out because package could not `import` the other packages.
Fixed in v.1.0.0 for ST3. Please update from Package Control!

**Closed as completed by rozboris** 2014-02-12 07:29 UTC
